### ISSUE TITLE
Readme 图片是不是连接少了什么？

### ISSUE THREAD

**Issue by wsdjeg** [msg7086/x265-Yuuki-Asuna#3]
`![](yande.re 211430.png)`

**Comment by msg7086** [comment]
Broken link due to Github changing their markdown parser.

Fixed by removing the space in the file name.

**Comment by wsdjeg** [comment]
Thanks for quick fix.


发送自 Outlook<http://aka.ms/weboutlook>


________________________________
发件人: Xinyue Lu <notifications@github.com>
发送时间: 2017年3月29日 11:55
收件人: msg7086/x265-Yuuki-Asuna
抄送: Wang Shidong; Author
主题: Re: [msg7086/x265-Yuuki-Asuna] Readme 图片是不是连接少了什么？ (#3)


Broken link due to Github changing their markdown parser.

Fixed by removing the space in the file name.

―
